site_name: '6417 Software Documentation'
theme: 
  name: 'material'
nav:
  - Software Dokumentation: 
    - Linksammlung: software/linksammlung.md
    - Tasks: software/tasks.md
    - Robots: 
      - 2017 : software/robots/2017.md
      - 2024 Wilhelm-Tell : software/robots/2024.md